### ISSUE TITLE
put_picture returns Koala::Facebook::ClientError

### ISSUE THREAD

**Issue by danielbonnell** [arsduo/koala#499] opened 2015-11-17 00:13 UTC
Hello,

I'm encountering a problem when I attempt to use the `put_picture` method to post a picture to a page.

I have the following code where `image` is a Ruby `File` object, `content_type` is the MIME type of the file, `post` is a string, and `page_name` is a string.

```
page_graph.put_picture(image, content_type, { message: post }, page_name)
```

This was working fine for me before, but now it seems to be broken. when I run the code, there is a delay of about 30 seconds before the following is returned:

```
Koala::Facebook::ClientError: <!DOCTYPE html>
<html lang="en" id="facebook">
  <head>
    <title>Facebook | Error</title>
    <meta charset="utf-8">
    <meta http-equiv="cache-control" content="no-cache">
    <meta http-equiv="cache-control" content="no-store">
    <meta http-equiv="cache-control" content="max-age=0">
    <meta http-equiv="expires" content="-1">
    <meta http-equiv="pragma" content="no-cache">
    <meta name="robots" content="noindex,nofollow">
    <style>
      html, body {
        color: #141823;
        background-color: #e9eaed;
        font-family: Helvetica, Lucida Grande, Arial,
                     Tahoma, Verdana, sans-serif;
        margin: 0;
        padding: 0;
        text-align: center;
      }

      #header {
        height: 30px;
        padding-bottom: 10px;
        padding-top: 10px;
        text-align: center;
      }

      #icon {
        width: 30px;
      }

      h1 {
        font-size: 18px;
      }

      p {
        font-size: 13px;
      }

      #footer {
        border-top: 1px solid #ddd;
        color: #9197a3;
        font-size: 12px;
        padding: 5px 8px 6px 0;
      }
    </style>
  </head>
  <body>
    <div id="header">
      <a href="//www.facebook.com/">
        <img id="icon" src="//static.xx.fbcdn.net/images/logos/facebook_2x.png" />
      </a>
    </div>
    <div id="core">
      <h1 id="sorry">Sorry, something went wrong.</h1>
      <p id="promise">
        We're working on it and we'll get it fixed as soon as we can.
      </p>
      <p id="back-link">
        <a id="back" href="//www.facebook.com/">Go Back</a>
      </p>
      <div id="footer">
        Facebook
        <span id="copyright">
          &copy; 2015
        </span>
        <span id="help-link">
          &#183;
          <a id="help" href="//www.facebook.com/help/">Help Center</a>
        </span>
      </div>
    </div>
    <script>
      document.getElementById('back').onclick = function() {
        if (history.length > 1) {
          history.back();
          return false;
        }
      };

      // Adjust the display based on the window size
      if (window.innerHeight < 80 || window.innerWidth < 80) {
        // Blank if window is too small
        document.body.style.display = 'none';
      };
      if (window.innerWidth < 200 || window.innerHeight < 150) {
        document.getElementById('back-link').style.display = 'none';
        document.getElementById('help-link').style.display = 'none';
      };
      if (window.innerWidth < 200) {
        document.getElementById('sorry').style.fontSize = '16px';
      };
      if (window.innerWidth < 150) {
        document.getElementById('promise').style.display = 'none';
      };
      if (window.innerHeight < 150) {
        document.getElementById('sorry').style.margin = '4px 0 0 0';
        document.getElementById('sorry').style.fontSize = '14px';
        document.getElementById('promise').style.display = 'none';
      };
    </script>
  </body>
</html> [HTTP 408]
from /Users/ACIDSTEALTH/.gem/ruby/2.0.0/gems/koala-2.2.0/lib/koala/api/graph_api.rb:515:in `block in graph_call'
```

I can't find anything in the docs or on StackOverflow about the problem. Not sure if it's a problem with my code, the API, or the gem. 

**Update**

I can't reproduce this any more. Maybe it was an issue with Facebook?

**Comment by arsduo** [comment] 2017-02-16 00:01
Hi! Sorry for the late response on several of these issues. I'm very glad to hear you can't reproduce it anymore. Facebook does amazing things with their API, but sometimes bugs do come (and go).

I'm going to close this for now, but let me know if there's anything I can help with around the gem!

**Closed by arsduo** 2017-02-16 00:01 UTC
