### ISSUE TITLE
SSL error

### ISSUE THREAD

**Issue by rusikf** [arsduo/koala#544] opened 2016-09-12 13:42 UTC
Hello ruby hackers

Some times during requests through koala gem I have this error
`Connection reset by peer - SSL_connect
`
How to fix it ? If I set 
`Koala.http_service.http_options = {
  :ssl => {
    :verify => false
  }
}`

It doesn't work.
If I also set ca_path to `/usr/lib/ssl`, it doesn't works also.

**Comment by Billy4195** [comment] 2016-09-12 14:32
Maybe you can reboot host or restart your rails server
I met this situation before, and after reboot the machine,then  it works

**Comment by rusikf** [comment] 2016-09-12 14:36
I have this problem on localhost, I tried restart and reboot - doesn't help

**Comment by Billy4195** [comment] 2016-09-12 14:50
I failed on localhost, too.
after reboot it works well.
Sorry, I have no idea to solve this problem :(

**Comment by stonko1994** [comment] 2016-09-14 14:58
I had the same problem since last week.

We have lots of requests fired in short time to get likes from multiple Posts of an user.

It looks like an raise condition maybe from Facebook.
After I turned on the Logs according to this [SO Answer](http://stackoverflow.com/a/13340867/2307466) the error was unexpected gone.

Don't know if this is an permanently fix but for now it works fine.

**Comment by tak1n** [comment] 2016-09-14 15:02
We are currently facing the same problem which occurs quite randomly.
We use koala in sidekiq workers.

E.g. when queuing up 100 jobs to fetch an app access token like this:

```ruby
Koala::Facebook::OAuth.new(
  APP_CONFIG['facebook']['consumer_key'],
  APP_CONFIG['facebook']['consumer_secret']
).get_app_access_token
```

some of them crash with the exception:

```
Faraday::ConnectionFailed: Connection reset by peer - SSL_connect
```

I tried to dig deeper into Faraday, Net::HTTP (which faraday uses internally) and the OpenSSL c extension from ruby itself, but didn't find something.

The CA path of the server is `/etc/ssl/certs` (which contains the same certs as `/usr/lib/ssl/certs`).
The funny thing is we observed that those errors started somewhat 4 days ago (without changing anything on our side, gem updates, ruby update etc etc)

I first thought maybe the certificate for facebook is outdated but that doesn't make quite sense as some of those requests work and some don't, so we are completely clueless right now where we should look further.

We will try to investigate further and update the issue with what we could find.

Library versions:
Koala 2.4.0
Faraday 0.9.2
Sidekiq 4.1.1
Rails: 4.2.7.1
OpenSSL 1.0.1t  3 May 2016
Ruby 2.3.1

**Comment by koni84** [comment] 2016-09-14 15:04
+1

**Comment by arsduo** [comment] 2017-02-17 03:46
`Connection reset by peer` means the connection got interrupted by a crash or network hiccup somewhere along the line. That's the nature of life on the Internet, unfortunately -- sometimes connections have problems. The only thing we can do is capture the error when it occurs and implement appropriate code to retry. 

See, for instance, http://stackoverflow.com/questions/1434451/what-does-connection-reset-by-peer-mean.

I'm going to close this, but if you do find a specific bug in Koala I'd be happy to address it!

**Closed by arsduo** 2017-02-17 03:46 UTC

**Comment by tak1n** [comment] 2017-02-17 07:51
@arsduo I think facebook had some issues with their servers as this didn't occurr anymore 2 days afterwards. So yea definitely not a bug in koala :)
