### ISSUE TITLE
Not able to always create a link to the original status

### ISSUE THREAD

**Issue by madeinstefano** [arsduo/koala#518] opened 2016-04-27 18:50 UTC
Hey, I'm trying to create a link back to the original facebook post, after fetching activities from given page feed. The code I'm using is the following:

``` ruby
POST_FIELDS = [
    'id', 
    'message', 
    'from.fields(id,name,link,picture,likes,bio)', 
    'type',
    'status_type', 
    'place',
    'picture', 
    'full_picture',
    'object_id',
    'parent_id',
    'source',
    'properties',
    'attachments',
    'link', 
    'created_time', 
    'updated_time',
    'comments.summary(true)', 
    'likes.summary(true)', 
    'shares',
    'message_tags']

client = Koala::Facebook::API.new("my secret key")

results = client.get_connections('mazda', 'feed', {limit: 10, fields: POST_FIELDS})
```

**A sample from the returning payload is this:**

``` javascript
[{"id"=>"337363685362_10156774442295363",
  "message"=>
   "The 2016 Mazda CX-3 has stiff competition in the 2016 Subaru Crosstrek, let alone the other heavy hitters in the crossover utility vehicle (CUV) such as Buick Encore, VW Tiguan, Jeep Renegade, Nissan Rogue, Ford Escape, Chevrolet Trax, and more.",
  "from"=>
   {"id"=>"176518270073",
    "name"=>"AutoNation",
    "link"=>"https://www.facebook.com/autonation/",
    "picture"=>
     {"data"=>
       {"is_silhouette"=>false,
        "url"=>
         "https://scontent.xx.fbcdn.net/hprofile-xta1/v/t1.0-1/p50x50/12246893_10156276701570074_4489930913675640439_n.jpg?oh=ac08e40eb961b9d26cc0c59b63349f1c&oe=57ABF0E6"}},
    "likes"=>22736},
  "type"=>"link",
  "status_type"=>"shared_story",
  "picture"=>
   "https://external.xx.fbcdn.net/safe_image.php?d=AQCp1takpn0b6VCt&w=130&h=130&url=https%3A%2F%2Fexpioncontent.s3.amazonaws.com%2F57AE151C8B63F51190FB14EE9CDE4529.jpg&cfs=1",
  "full_picture"=>
   "https://external.xx.fbcdn.net/safe_image.php?d=AQDjqPxWkD2u2vp-&url=https%3A%2F%2Fexpioncontent.s3.amazonaws.com%2F57AE151C8B63F51190FB14EE9CDE4529.jpg",
  "link"=>"http://expi.co/0vWBs",
  "created_time"=>"2016-04-27T17:00:07+0000",
  "updated_time"=>"2016-04-27T17:00:07+0000",
  "message_tags"=>
   {"9"=>[{"id"=>"337363685362", "name"=>"Mazda", "type"=>"page", "offset"=>9, "length"=>5}],
    "54"=>[{"id"=>"108114182550402", "name"=>"Subaru", "type"=>"page", "offset"=>54, "length"=>6}],
    "153"=>[{"id"=>"75764238259", "name"=>"Buick", "type"=>"page", "offset"=>153, "length"=>5}],
    "193"=>[{"id"=>"150078858341748", "name"=>"Nissan", "type"=>"page", "offset"=>193, "length"=>6}],
    "220"=>[{"id"=>"77589292295", "name"=>"Chevrolet", "type"=>"page", "offset"=>220, "length"=>9}]},
  "likes"=>{"data"=>[], "summary"=>{"total_count"=>0, "can_like"=>true, "has_liked"=>false}},
  "comments"=>{"data"=>[], "summary"=>{"order"=>"ranked", "total_count"=>0, "can_comment"=>true}},
  "attachments"=>
   {"data"=>
     [{"description"=>
        "In a comparison of All-Wheel Drive vehicles, we pitch the 2016 Mazda CX-3 AWD vs. 2016 Subaru Crosstrek in this week's head-to-head. Click here for more!",
       "media"=>
        {"image"=>
          {"height"=>325,
           "src"=>
            "https://external.xx.fbcdn.net/safe_image.php?d=AQCPB5Czo16D4Ddf&w=720&h=720&url=https%3A%2F%2Fexpioncontent.s3.amazonaws.com%2F57AE151C8B63F51190FB14EE9CDE4529.jpg&cfs=1",
           "width"=>325}},
       "target"=>
        {"url"=>
          "http://www.facebook.com/l.php?u=http%3A%2F%2Fexpi.co%2F0vWBs&h=rAQFyQ2Ho&s=1&enc=AZNhkzQCQqMr9E-fOJVQk1us-BZA9YlTMTFz0474e7f7jsrnR01wznOtxYw9fu4wFxoGqh240aIWHOpc_QmTEKgn"},
       "title"=>"Head to Head: 2016 Mazda CX-3 AWD vs. 2016 Subaru Crosstrek",
       "type"=>"share",
       "url"=>
        "http://www.facebook.com/l.php?u=http%3A%2F%2Fexpi.co%2F0vWBs&h=rAQFyQ2Ho&s=1&enc=AZNhkzQCQqMr9E-fOJVQk1us-BZA9YlTMTFz0474e7f7jsrnR01wznOtxYw9fu4wFxoGqh240aIWHOpc_QmTEKgn"}]}}]
```

So, to create a link to the original status, I'm joining "http://facebook.com/" + the `id` property from each status.

This works great unless the status have `message_tags` with type `page`, in this case, the id redirect to a 404 page. 

After searching for this error, I figured out that in this scenario, the first half of the status `id`, which is the user `id`, is from the page mentioned in the status and not from the author.

Do you know if this is intentional in the facebook API, or is an error by them, or maybe a parsing error by Koala? And do you know a reliable way to create a link back to the original status?

**Comment by christianstanfield** [comment] 2016-12-05 20:31
Did you ever resolve this issue? I noticed this as well. I can confirm on facebook's graph explorer the correct post id is returned, so it must be a bug in koala

**Comment by christianstanfield** [comment] 2016-12-05 22:54
I've noticed this same thing. It does seem that Facebook isn't consistent with their post ids. When requesting posts in a batch I've even gotten back a different id for the post I just requested by id. I thought it was Koala parsing at first but I can reproduce it in the graph explorer.

**Comment by arsduo** [comment] 2017-02-15 23:52
Thanks, @christanstanfield. (And apologies about the late response!) Since it's a Facebook issue I'm going to close the issue, but if you do find anything related to this with Koala please reopen it.

**Closed by arsduo** 2017-02-15 23:52 UTC

**Comment by atishay5395** [comment] 2017-07-27 19:08
Hi arsduo, Im not able to set the fields using Koala. Can u help me out? I just get three parameters - id, created_time and message

**Comment by christianstanfield** [comment] 2017-08-27 19:01
@atishay5395 You should be able to request specific fields for any relevant endpoint as a fields hash identical to the example above
