### ISSUE TITLE
Same as issue #523

### ISSUE THREAD

**Issue by harishbollina** [arsduo/koala#598] opened 2017-03-07 13:46 UTC
Hello All,

I am trying to do the same thing(Adding thumbnail to video) from Graph API and I am receiving the error msg: "(#100) Invalid image format. It should be an image file data."
The Images that I am using as source are :
https://www.facebook.com/images/fb_icon_325x325.png
and another Image which is in my local host. Either way is not working for me. Please help what I am doing wrong here....
Also, please provide any source you have to add thumbnail to a video in FB...Thanks in Advance

**Comment by arsduo** [comment] 2017-03-07 14:36
This is a duplicate of #543 with the same comment as there, so I'm closing this.

**Closed by arsduo** 2017-03-07 14:36 UTC
